Load config variables from .env file with `python-dotenv`
iScsc/iscsc.fr-blog-notify pull request #6
Opened 2023-04-24 13:21 UTC by ctmbl

2023-04-25 15:44 UTC, gbrivady requested changes

2023-04-25 15:44 UTC, gbrivady commented on README.md
> +In a `.env` file, specify your Discord token and the channel ID in which the bot needs to post notifications. You can also chose the refresh timer, in minutes.
Refresh timer is still configured by python, and not the .env file

2023-04-26 09:06 UTC, ctmbl commented on README.md
> +In a `.env` file, specify your Discord token and the channel ID in which the bot needs to post notifications. You can also chose the refresh timer, in minutes.
tks for noticing it I'll update it!

2023-04-26 09:15 UTC, ctmbl commented on README.md
> +In a `.env` file, specify your Discord token and the channel ID in which the bot needs to post notifications. You can also chose the refresh timer, in minutes.
done in [924729a](https://github.com/iScsc/iscsc.fr-blog-notify/pull/6/commits/924729aecbc26e5868f5549ee1b7715b6bf7c67e)

2023-04-26 16:35 UTC, gbrivady approved these changes

2023-04-26 21:33 UTC, merged